### ISSUE TITLE
Update issue

### ISSUE THREAD

**Issue by Ash258** [Ash258/Scoop-JetBrains#6]
> when there is a patch update, currently it will report error: Failed to prepare an update: Temp directory inside installation

https://github.com/Ash258/Scoop-JetBrains/issues/4#issuecomment-475332943

/cc @Retia-Adolf

When did you experience this error? What does produce it?

**Comment by Ash258** [comment]
https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000173724-Cannot-update-to-Idea-2017-1-1

**Comment by Retia-Adolf** [comment]
I think I have said it there, maybe not clear enough.

1. At version 2019.1-191.6183.20

2. Opened IntelliJ IDEA, it notified a patch update in itself, clicked to download, when downloaded complete, it reported that error `Failed to prepare an update: Temp directory inside installation`

it is caused by that profile directory is at the same place of IntelliJ IDEA's root directory.
```
intellij-idea-eap-portable
    └current
       ├ bin
       ├ lib
       ├ (...)
       └ profile
```

I adjusted my installation to keep `profile` out of IntelliJ IDEA's root directory, started IntelliJ IDEA again, clicked to update, then there is no error.
```
intellij-idea-eap-portable
    └current
       ├ ide
       │  ├ bin
       │  ├ lib
       │  ├ (...)
       └ profile
```
